---
# External Ansible collections and roles needed by the playbooks and roles in this repository
collections:
  - name: community.docker
    version: 3.8.0
roles:
  - name: geerlingguy.pip
    version: 3.0.3
  - name: geerlingguy.docker
    version: 7.1.0
